---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: lab.ebox86.com
  source:
    repoURL: https://kubernetes-sigs.github.io/descheduler
    chart: descheduler
    targetRevision: "*"
    helm:
      values: |
        kind: CronJob
        schedule: "*/30 * * * *"
        deschedulerPolicy:
          profiles:
            - name: default
              pluginConfig:
                - name: DefaultEvictor
                  args:
                    ignorePvcPods: true
                    evictLocalStoragePods: false
                - name: RemoveDuplicates
                - name: RemovePodsViolatingInterPodAntiAffinity
                - name: RemovePodsViolatingNodeAffinity
                  args:
                    nodeAffinityType:
                      - requiredDuringSchedulingIgnoredDuringExecution
              plugins:
                balance:
                  enabled:
                    - RemoveDuplicates
                deschedule:
                  enabled:
                    - RemovePodsViolatingInterPodAntiAffinity
                    - RemovePodsViolatingNodeAffinity
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
