---
# sync-wave: -1 so the controller is running before metallb-config applies CRDs
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: lab.ebox86.com
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: "0.*"
    helm:
      values: |
        speaker:
          tolerations:
            - key: node-role.kubernetes.io/master
              effect: NoSchedule
              operator: Exists
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
