---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfd-config
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: lab.ebox86.com
  source:
    repoURL: https://github.com/ebox86/ebox86-infra.git
    targetRevision: main
    path: k8s/nfd
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-nfd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
