---
# AppProject scoping all lab.ebox86.com workloads.
# Limits source repos and destination clusters ArgoCD apps can target.
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: lab.ebox86.com
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Homelab workloads

  sourceRepos:
    - https://github.com/ebox86/ebox86-infra.git
    - https://bitnami-labs.github.io/sealed-secrets
    - https://grafana.github.io/helm-charts
    - https://prometheus-community.github.io/helm-charts
    - https://metallb.github.io/metallb
    - https://kubernetes-sigs.github.io/node-feature-discovery/charts
    - https://kubernetes-sigs.github.io/descheduler
    - https://grafana.github.io/loki-helm-chart

  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
